# Generated by Django 4.2.3 on 2023-08-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=50)),
                ('edob', models.DateField()),
                ('egender', models.CharField(max_length=10)),
                ('eemail', models.EmailField(max_length=254, unique=True)),
                ('ephone', models.CharField(max_length=10, unique=True)),
                ('eusername', models.CharField(max_length=20)),
                ('epassword', models.CharField(max_length=50, unique=True)),
                ('eimage', models.ImageField(upload_to='images')),
            ],
            options={
                'db_table': 'employeedetails',
            },
        ),
        migrations.CreateModel(
            name='MemberDetails',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=50)),
                ('mdob', models.DateField()),
                ('mgender', models.CharField(max_length=10)),
                ('memail', models.EmailField(max_length=254, unique=True)),
                ('mphone', models.CharField(max_length=10, unique=True)),
                ('musername', models.CharField(max_length=50)),
                ('mpassword', models.CharField(max_length=50, unique=True)),
                ('mtrainerid', models.CharField(max_length=20)),
                ('mimage', models.ImageField(upload_to='images')),
            ],
            options={
                'db_table': 'memberdetails',
            },
        ),
    ]
