# Generated by Django 4.2.7 on 2023-11-12 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationTable',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryTable',
            fields=[
                ('enquiryId', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=10)),
                ('enquiryStatement', models.CharField(max_length=1000)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.registrationtable')),
            ],
        ),
    ]
